@startuml


!include <tupadr3/common>
!include <tupadr3/devicons/angular>
!include <tupadr3/devicons/html5>
!include <tupadr3/devicons/dotnet>
!include <tupadr3/devicons/java>
!include <tupadr3/devicons/msql_server>
!include <tupadr3/font-awesome/server>
!include <tupadr3/font-awesome/envelope>


@enduml